import React from 'react'
import { createRoot } from 'react-dom/client'
import { ThemeProvider } from '@mui/material/styles'
import CssBaseline from '@mui/material/CssBaseline'
import { SorbProvider, PreviewBanner } from '@sorb/leaf'
import { sorbConfig } from './src/sorbConfig'
import { theme } from './src/theme'
import { App } from './src/App'

// Committed Janes Jeans CSS custom properties (--color-*, --button-*, …).
// Generated by `npm run tokens`; a Sorb preview push swaps these at runtime.
import './src/tokens/generated/variables.css'

// MUI's own cssVariables:true stylesheet is injected by ThemeProvider at
// render time. This override layer (also `npm run tokens` output) MUST be
// imported AFTER MUI's styles are registered so its `:root` block wins the
// cascade and re-points --mui-* vars at the Janes Jeans ones above. Emotion
// injects MUI's <style> tag on first render (not at import time), so a plain
// static <link>/import ordering isn't reliable — see `MuiVarsOverride` below,
// which renders this stylesheet as the LAST <style> tag in <head> instead.
import muiVarsCss from './src/tokens/generated/mui-vars.css?raw'

const MuiVarsOverride = () => <style data-jj-mui-vars>{muiVarsCss}</style>

// Provider stack:
//   SorbProvider          @sorb/leaf — preview/verify context (pushes JJ
//                         token custom properties onto :root during a preview)
//     ThemeProvider       MUI — computes/injects its own --mui-* vars from
//                         the (pre-sorb: hardcoded / sorb-migrated: JJ-sourced)
//                         theme.js seed values
//       CssBaseline
//       App
//   MuiVarsOverride       the indirection layer, rendered last so its <style>
//                         tag is the last sibling MUI's engine has emitted so
//                         far — re-points covered --mui-* vars at JJ vars
//   PreviewBanner
createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <SorbProvider config={sorbConfig}>
      <ThemeProvider theme={theme}>
        <CssBaseline />
        <App />
      </ThemeProvider>
      <MuiVarsOverride />
      <PreviewBanner />
    </SorbProvider>
  </React.StrictMode>,
)
