import StyleDictionary from 'style-dictionary'
import {
  SORB_RESOLVED,
  SORB_TOKENSET,
  SORB_VERSIONS,
  SORB_SET_META,
  sorbResolved,
  sorbTokenSet,
  sorbVersions,
  sorbSetMeta,
} from '@sorb/seed'

StyleDictionary.registerParser(sorbSetMeta)
StyleDictionary.registerFormat({ name: SORB_RESOLVED, format: sorbResolved })
StyleDictionary.registerFormat({ name: SORB_TOKENSET, format: sorbTokenSet })
StyleDictionary.registerFormat({ name: SORB_VERSIONS, format: sorbVersions })

/**
 * `sorb/mui-vars` — LOCAL format (promotion-candidate, not yet in @sorb/seed).
 *
 * MUI v6 `createTheme({ cssVariables: true })` rejects `var(...)` strings as
 * palette input (it needs real colors to compute contrast/tonal variants —
 * verified via spike, see README §MUI integration). So the mechanism here is
 * an INDIRECTION layer: MUI still computes its own `--mui-*` custom
 * properties from hardcoded seed values, and this format emits a *second*,
 * later-cascading `:root` block that re-points each covered `--mui-*` var at
 * the matching Janes Jeans token via `var(--jj-token, <mui-fallback>)`. Any
 * component reading `var(--mui-palette-primary-main)` transitively resolves
 * through to the JJ token, and the Sorb bridge's runtime push (which sets
 * `--color-*` on `:root`) re-themes it live with zero MUI reinitialization.
 *
 * Coverage (verified against @mui/material 6.5.0's actual `theme.vars` shape):
 *   COVERED   — palette.{primary,secondary,error,warning,info,success}.{main,dark,contrastText},
 *               palette.background.{default,paper}, palette.text.{primary,secondary},
 *               palette.divider, shape.borderRadius.
 *   NOT COVERED — typography (fontFamily/fontSize/fontWeight per variant — MUI v6 does not
 *               expose these as CSS vars by default), spacing function, transitions, zIndex,
 *               breakpoints. These stay JS-only theme values; a live preview cannot re-theme them.
 */
const sorbMuiVars = ({ dictionary }) => {
  const byPath = (path) => dictionary.allTokens.find((t) => t.path.join('.') === path)
  const cssVar = (path, fallback) => {
    const token = byPath(path)
    return token ? `var(--${token.name}, ${fallback})` : fallback
  }

  const map = [
    ['--mui-palette-primary-main', cssVar('color.brand', '#1976d2')],
    ['--mui-palette-primary-dark', cssVar('color.brand-hover', '#1565c0')],
    ['--mui-palette-primary-contrastText', cssVar('color.brand-contrast', '#fff')],
    ['--mui-palette-secondary-main', cssVar('color.accent', '#9c27b0')],
    ['--mui-palette-secondary-dark', cssVar('color.accent-hover', '#7b1fa2')],
    ['--mui-palette-secondary-contrastText', cssVar('color.accent-contrast', '#fff')],
    ['--mui-palette-error-main', cssVar('color.danger', '#d32f2f')],
    ['--mui-palette-error-dark', cssVar('color.danger-hover', '#c62828')],
    ['--mui-palette-success-main', cssVar('color.success', '#2e7d32')],
    ['--mui-palette-success-dark', cssVar('color.success-hover', '#1b5e20')],
    ['--mui-palette-background-default', cssVar('color.surface', '#fff')],
    ['--mui-palette-background-paper', cssVar('color.surface-raised', '#fff')],
    ['--mui-palette-text-primary', cssVar('color.ink', 'rgba(0,0,0,0.87)')],
    ['--mui-palette-text-secondary', cssVar('color.ink-muted', 'rgba(0,0,0,0.6)')],
    ['--mui-palette-divider', cssVar('color.border', 'rgba(0,0,0,0.12)')],
    ['--mui-shape-borderRadius', cssVar('radius.control', '4px')],
  ]

  const lines = map.map(([muiVar, value]) => `  ${muiVar}: ${value};`).join('\n')

  return `/**
 * AUTOGENERATED by sd.config.js (sorb/mui-vars format). Do not hand-edit.
 * Maps MUI's cssVariables:true output vars -> Janes Jeans token vars, so a
 * Sorb preview push against --color-*/--radius-* cascades through to MUI.
 * Loaded AFTER MUI's own theme stylesheet — see main.jsx import order.
 */
:root, [data-mui-color-scheme] {
${lines}
}
`
}

StyleDictionary.registerFormat({ name: 'sorb/mui-vars', format: sorbMuiVars })

/** @type {import('style-dictionary').Config} */
export default {
  source: [
    'node_modules/@metatoy/janes-jeans/tokens/primitive.json',
    'node_modules/@metatoy/janes-jeans/tokens/semantic.json',
    'node_modules/@metatoy/janes-jeans/tokens/component.json',
  ],
  parsers: [SORB_SET_META],
  platforms: {
    css: {
      transformGroup: 'css',
      buildPath: 'src/tokens/generated/',
      files: [{ destination: 'variables.css', format: 'css/variables', options: { outputReferences: true } }],
    },
    js: {
      transformGroup: 'css',
      buildPath: 'src/tokens/generated/',
      files: [{ destination: 'tokens.js', format: SORB_TOKENSET }],
    },
    sorb: {
      transformGroup: 'css',
      buildPath: '.sorb/',
      files: [
        { destination: 'resolved.json', format: SORB_RESOLVED },
        { destination: 'versions.json', format: SORB_VERSIONS },
      ],
    },
    mui: {
      transformGroup: 'css',
      buildPath: 'src/tokens/generated/',
      files: [{ destination: 'mui-vars.css', format: 'sorb/mui-vars' }],
    },
  },
}
